In [3]:
import numpy as np
import copy
import math

In [4]:
def check_pos_def(A):
    matr_len = np.shape(A)[0]
    M = copy.deepcopy(A)  
    
    curent_len = matr_len
    while(curent_len > 0):
        if(curent_len == matr_len):
            determ = np.linalg.det(M)
        else:
            M = np.delete(M, curent_len, axis = 0)
            M = np.delete(M, curent_len, axis = 1)
            determ = np.linalg.det(M)
        
        if(determ <= 0):
            return False
        curent_len = curent_len - 1
    
    return True

def make_E_matr(A):
    E_matr = np.ones(A.shape)

    for i in range(A.shape[0]):
        for j in range(A.shape[0]):
            if(not(i == j)):
                E_matr[i][j] = E_matr[i][j] - 1
    return E_matr

def iter_solve(R, iter_F, real_solution, accuarcy, iter_solution, k):
    k = k + 1
    print("Iteration number", k)
    iter_solution = np.dot(R, iter_solution) + iter_F
    print(iter_solution)
    
    if(abs(np.linalg.norm(iter_solution) - np.linalg.norm(real_solution)) < accuarcy):
        return iter_solution
    else:
        iter_solution = iter_solve(R, iter_F, real_solution, accuarcy, iter_solution, k)
    

In [5]:
A = np.array([[-2., 1.],[0., 2.]])
F = np.array([[3.], [1.]])
Uo = np.array([[0.], [0.]])
E = 10 ** (-3)


if(not check_pos_def(A)):
    F = np.dot(A.transpose(), F)
    A = np.dot(A.transpose(), A)
    
eigenval = np.linalg.eig(A)[0]


tau = 2 / (np.max(eigenval) + np.min(eigenval))

q_optimal = (np.max(eigenval) - np.min(eigenval)) / (np.max(eigenval) + np.min(eigenval))

Eo = np.dot(A, Uo) - F



num_steps = int(math.log(E / np.linalg.norm(Eo), q_optimal)) + 1

solution = np.linalg.solve(A, F)

print("Оптимальный шаг равен", tau)
print("Оптимальное q равно ", q_optimal)
print(f"Число шагов для достижения точности (E = {E}) >= {num_steps}")
print("Решение системы: \n", solution) 

Оптимальный шаг равен 0.2222222222222222
Оптимальное q равно  0.4581228472908513
Число шагов для достижения точности (E = 0.001) >= 12
Решение системы: 
 [[-1.25]
 [ 0.5 ]]


In [6]:
solution = np.linalg.solve(A, F)

E_matr = make_E_matr(A)

R = E_matr - tau * A
iter_F = tau * F

k = 0
iter_solution = iter_solve(R, iter_F, solution, E, Uo, k)
 

Iteration number 1
[[-1.33333333]
 [ 1.11111111]]
Iteration number 2
[[-0.98765432]
 [ 0.39506173]]
Iteration number 3
[[-1.26748971]
 [ 0.62825789]]
Iteration number 4
[[-1.1949398 ]
 [ 0.47797592]]
Iteration number 5
[[-1.25367068]
 [ 0.52691832]]
Iteration number 6
[[-1.23844415]
 [ 0.49537766]]
Iteration number 7
[[-1.25077039]
 [ 0.50564952]]
Iteration number 8
[[-1.2475747 ]
 [ 0.49902988]]
Iteration number 9
[[-1.25016169]
 [ 0.5011857 ]]
